import { useMemo, useState, type ReactNode } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Search } from "lucide-react";
import ChapterHeader from "@/components/shared/ChapterHeader";
import DefCard from "@/components/shared/DefCard";
import TokenChip from "@/components/shared/TokenChip";

interface Term {
  term: string;
  /** Verbatim definition — plain text used for filtering. */
  text: string;
  /** Rich rendering (defaults to `text`); chips for sub-lists per spec S10. */
  body?: ReactNode;
}

function InlineChip({ children }: { children: ReactNode }) {
  return (
    <TokenChip className="mx-0.5 px-1.5 py-0.5 text-[12px]">{children}</TokenChip>
  );
}

/** The 21 glossary terms, verbatim, in source (pedagogical) order. */
const TERMS: Term[] = [
  { term: "Dataset", text: "The examples used for training or evaluation." },
  { term: "Batch", text: "A group of examples processed together." },
  {
    term: "Epoch",
    text: "One pass through a dataset. For extremely large LLM datasets, training may be discussed more often in tokens and steps than epochs.",
    body: (
      <>
        One pass through a dataset. For extremely large LLM datasets, training
        may be discussed more often in <InlineChip>tokens</InlineChip> and{" "}
        <InlineChip>steps</InlineChip> than epochs.
      </>
    ),
  },
  { term: "Parameter", text: "A number learned by the model." },
  {
    term: "Hyperparameter",
    text: "A setting chosen by humans, such as: learning rate, model size, batch size, number of layers, context length.",
    body: (
      <>
        A setting chosen by humans, such as:
        <span className="mt-2.5 flex flex-wrap gap-1.5">
          {["learning rate", "model size", "batch size", "number of layers", "context length"].map(
            (chip) => (
              <InlineChip key={chip}>{chip}</InlineChip>
            )
          )}
        </span>
      </>
    ),
  },
  { term: "Loss", text: "A numerical measure of error." },
  { term: "Gradient", text: "The direction in which parameters should change." },
  { term: "Optimizer", text: "The algorithm that updates parameters." },
  { term: "Learning rate", text: "How large each parameter update is." },
  {
    term: "Overfitting",
    text: "The model memorizes training examples but fails on new data.",
  },
  { term: "Generalization", text: "The model performs well on new examples." },
  { term: "Regularization", text: "Techniques that discourage overfitting." },
  {
    term: "Distribution shift",
    text: "The real-world inputs differ from the training data.",
  },
  { term: "Embedding", text: "A learned vector representation." },
  {
    term: "Latent representation",
    text: "Internal information encoded by the model but not directly visible.",
  },
  { term: "Checkpoint", text: "A saved version of the model during training." },
  {
    term: "Rollout",
    text: "An attempted trajectory generated by a model or agent.",
  },
  {
    term: "Reward model",
    text: "A model that predicts how good an answer or action is.",
  },
  { term: "Verifier", text: "A system that checks whether an output is correct." },
  {
    term: "Benchmark",
    text: "A standardized collection of evaluation tasks.",
  },
  {
    term: "Ablation",
    text: "An experiment that removes one component to test whether it actually matters.",
  },
];

/**
 * Chapter 10 — Important concepts you should understand (segment-d spec S10).
 * Sticky client-side filter bar (term + definition match) above a 3-col
 * DefCard grid; non-matching cards collapse with a 0.25s layout animation.
 */
export default function Glossary() {
  const [query, setQuery] = useState("");

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return TERMS;
    return TERMS.filter(
      (t) =>
        t.term.toLowerCase().includes(q) || t.text.toLowerCase().includes(q)
    );
  }, [query]);

  return (
    <section id="chapter-10" className="border-t border-line bg-paper-deep">
      <div className="page-col py-14 md:py-20">
        <ChapterHeader
          kicker="CHAPTER 10"
          title="Important concepts you should understand"
          number="10"
          lede={
            <p className="text-[17.5px] leading-[1.75] max-md:text-[16px]">
              These are the core vocabulary of modern ML:
            </p>
          }
        />

        {/* Sticky filter bar */}
        <motion.div
          initial={{ y: -8, opacity: 0 }}
          whileInView={{ y: 0, opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.3 }}
          className="sticky top-[72px] z-30 mt-10 md:mt-12"
        >
          <div className="flex items-center gap-3 rounded-full border border-line bg-paper-raise/95 px-4 py-2.5 shadow-lift backdrop-blur-sm">
            <Search className="size-4 shrink-0 text-ink-faint" aria-hidden="true" />
            <label htmlFor="glossary-filter" className="sr-only">
              Filter glossary terms
            </label>
            <input
              id="glossary-filter"
              type="search"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="filter terms…"
              autoComplete="off"
              className="w-full bg-transparent font-mono text-[13.5px] text-ink outline-none placeholder:text-ink-faint"
            />
            <span
              aria-live="polite"
              className="shrink-0 font-mono text-[12px] font-medium tabular-nums text-ink-faint"
            >
              {filtered.length} / {TERMS.length}
            </span>
          </div>
        </motion.div>

        <motion.div
          layout
          className="mt-8 grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3"
        >
          <AnimatePresence mode="popLayout">
            {filtered.map((t) => (
              <motion.div
                key={t.term}
                layout
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{ duration: 0.25 }}
              >
                <DefCard term={t.term} className="h-full">
                  {t.body ?? t.text}
                </DefCard>
              </motion.div>
            ))}
          </AnimatePresence>
        </motion.div>

        {filtered.length === 0 && (
          <p className="mt-10 text-center font-mono text-[13px] text-ink-faint">
            No terms match “{query}”.
          </p>
        )}
      </div>
    </section>
  );
}
